version: "2"

services:
  interlock:
    image: ehazlett/interlock:1.2.0
    command: -D run --discovery consul://192.168.99.10:8500
    ports: ["8080"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/boot2docker:/var/lib/boot2docker:ro"
      - "/home/docker/interlock:/etc/interlock:ro"
    networks:
      - edge-tier
    labels:
      - "com.docker.swarm.reschedule-policies=on-node-failure"

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - "80:80"
    labels:
      - "interlock.ext.name=nginx"
    environment:
      - "constraint:custom.role==public"
    networks:
      - edge-tier

networks:
  edge-tier:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.102.0.0/16
