rexray:
  logLevel: warn
  storageDrivers:
  - virtualbox
  volume:
    mount:
      preempt: true
virtualbox:
  endpoint: http://10.0.2.2:18083
  tls: false
  volumePath: /tmp/rexray
  controllerName: SATA
